version: "3"

services:
  mysql:
    build: .
    container_name: mysql-db
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_DATABASE=nuanxin
      - MYSQL_USER=luwu
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3306:3306"
    volumes:
      - mysql-log:/var/log/mysql
      - mysql-storage:/var/lib/mysql
      
volumes:
  mysql-log:
  mysql-storage: